apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: pesbuk-production
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: YWRtaW4xMjM0
  DB_NAME: ZGJzb3NtZWQ=
  DB_HOST: cGVzYnVrLmNmcWpleW1xdmtmcS5hcC1zb3V0aGVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
